
project = 'test-scage'

model_folder = '/media/deepstation/843cad10-f308-49f6-b896-b1ac1470af80/anipose_demo/hand-demo-dlc-TuthillLab-2019-08-05' 

nesting = 1
video_extension = 'mp4'

[calibration]
# checkerboard / charuco / aruco
board_type = "charuco"

# width and height of grid
board_size = [10, 7]

# number of bits in the markers, if aruco/charuco
board_marker_bits = 4

# number of markers in dictionary, if aruco/charuco
board_marker_dict_number = 50

# length of marker side
board_marker_length = 18.75 # mm

# If aruco, length of marker separation
# board_marker_separation_length = 1 # mm

# If charuco or checkerboard, square side length
board_square_side_length = 25 # mm

animal_calibration = false

fisheye = false

[labeling]
scheme = [
   # Face
   ["nose", "left_eye", "right_eye", "left_ear", "right_ear"],

   # Torso
   ["left_shoulder", "right_shoulder", "left_hip", "right_hip", "left_shoulder"],

   # Left Arm
   ["left_shoulder", "left_elbow", "left_wrist"],

   # Right Arm
   ["right_shoulder", "right_elbow", "right_wrist"],

   # Left Leg
   ["left_hip", "left_knee", "left_ankle"],

   # Right Leg
   ["right_hip", "right_knee", "right_ankle"]
]

[filter]
enabled = true
type = "viterbi"

[triangulation]
triangulate = true
cam_regex = '-cam([0-7])'
cam_align = "4"
ransac = false
optim = true
constraints = [
   # Face and Head
   ["nose", "left_eye"], ["nose", "right_eye"], ["left_eye", "right_eye"],
   ["nose", "left_ear"], ["nose", "right_ear"],
   ["left_eye", "left_ear"], ["right_eye", "right_ear"],
   ["left_ear", "right_ear"],

   # Shoulders to ears
   ["left_shoulder", "left_ear"], ["right_shoulder", "right_ear"],

   # Body and limbs
   ["left_shoulder", "right_shoulder"], ["left_shoulder", "left_elbow"],
   ["left_elbow", "left_wrist"], ["right_shoulder", "right_elbow"],
   ["right_elbow", "right_wrist"], ["left_hip", "right_hip"],
   ["left_hip", "left_knee"], ["left_knee", "left_ankle"],
   ["right_hip", "right_knee"], ["right_knee", "right_ankle"]
]
constraints_weak = [
   ["left_shoulder", "left_hip"], ["right_shoulder", "right_hip"],
   ["left_shoulder", "right_hip"], ["right_shoulder", "left_hip"],
   ["left_shoulder", "right_shoulder"], ["left_hip", "right_hip"],

   # Extra facial stability
   ["left_eye", "nose"], ["right_eye", "nose"], ["left_eye", "left_ear"],
   ["right_eye", "right_ear"], ["left_ear", "right_ear"]
]
scale_smooth = 3
scale_length = 5
scale_length_weak = 2
reproj_error_threshold = 3
score_threshold = 0.5
n_deriv_smooth = 2